[package]
name = "sztorm_rl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sztorm = {path = "../sztorm"}
tch = "0.13.0"
log = "0.4.19"