[package]
name = "amfi_rl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amfi = {path = "../amfi" }
tch = "0.14.0"
log = "0.4.19"
thiserror = "1.0.40"
rand = "0.8.5"